version: '3.9'
services:
  daily-web:
    image: daily-web:latest
    container_name: daily-web
    build: 
      context: ..
      dockerfile: ./docker/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
  
  daily-server:
    image: daliy-server:latest
    container_name: daily-server
    build: 
      context: ..
      dockerfile: ./docker/server/Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - daily-db
  
  daily-db:
    image: postgres:13.2
    container_name: daily-db
    restart: always
    environment:
      POSTGRES_PASSWORD: hellodaily
      POSTGRES_USER: postgres
      POSTGRES_DB: daily
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data